добавить wndproc в mainwindow
profcomff/print-winapp pull request #54
Opened 2023-04-25 21:22 UTC by JR000

Теперь MainWindow может обрабатывать события WinApi Добавлена блокировка CTRL+F4 и автоматическое восстановление mainwindow-ом фокуса в случае потери

2023-04-27 20:17 UTC, mrerro requested changes
первый рауд ревью

2023-04-27 20:17 UTC, mrerro commented on PrinterApp/MainWindow.xaml.cs
> +                this.Activate();
По тестировал еще в сторону WM_NCACTIVATE, еще дополнительно к активации окна добавил чтобы вроде как фокус клавиатуры возвращался, но безуспешно, не нажав на окно ввод не продолжается.

2023-04-27 20:17 UTC, mrerro commented on PrinterApp/MainWindow.xaml.cs
> +                this.Activate();
Еще момент, что когда запуск из студии, то она помогает переносить фокус назад на приложение. Для чистоты следует запускать exe из bin вручную

2023-04-27 20:45 UTC, mrerro commented on PrinterApp/MainWindow.xaml.cs
> +                this.Activate();
Как посоветовал @dyakovri . Так как у нас `fullscreen` приложение которое всегда сверху то при получении события [WM_NCACTIVATE](https://learn.microsoft.com/ru-ru/windows/win32/winmsg/wm-ncactivate) c `wParam` == 0 мы с имитируем нажатие мыши классом https://stackoverflow.com/a/7121314 
![image](https://user-images.githubusercontent.com/13213573/234986417-0d676e73-3ae9-4a83-8fa9-759c6bd5196d.png)

2023-05-04 16:25 UTC, JR000 commented on PrinterApp/MainWindow.xaml.cs
> +                this.Activate();
Activate всё-таки тоже нужно вызывать: без него не получается. А так, судя по всему, достаточно WM_KILLFOCUS

2023-05-05 05:21 UTC, mrerro requested changes
Второй раунд ревью. Осталась пара мелочей. Заметь что main ушел дальше и нужно еще сделать rebase ветки.

2023-05-05 05:21 UTC, mrerro commented on PrinterApp/MouseOperations.cs
> +
Добавить строку `namespace PrinterApp;` с отступом до и после.

2023-05-05 05:21 UTC, mrerro commented on PrinterApp/MainWindow.xaml.cs
> +                MessageBox.Show("ОШИБКА: не удалось получить хэндл окна");
Заменить на `Log.Error($"{GetType().Name} {MethodBase.GetCurrentMethod()?.Name}: не удалось получить хэндл окна");`

2023-05-05 05:21 UTC, mrerro commented on PrinterApp/MainWindow.xaml.cs
> +                Environment.Exit(1);
Убрать так как это не приоритетная функция для прекращения работы программы (вообще скорее всего мы никогда не попадем в этот else, но проверить на возможность каста надо), а то можно получить утром после автоматического обновления что программа не запущена.  
Заменить на отправку сообщения в маркетинг `Marketing.HwndSourceError();`. Предварительно добавив в `Marketing.cs` новую функцию
```c#
public static void HwndSourceError()
{
    Post(
        action: "print terminal failed to get window HwndSource",
        status: "error");
}
```
"print terminal" в `action` обязательное начало строки для сообщения от терминала.

2023-05-06 12:35 UTC, mrerro requested changes
этот коммит мердж надо вообще убрать `Merge branch 'main' into patch-1`
commit ce4cba51a7f280e331593861a18456dd7533c414 он получился с проблемами код не собирается 
![image](https://user-images.githubusercontent.com/13213573/236624268-39cacba1-e00b-4336-a9a8-2af6a86feb2b.png)
нужно сделать не мердж, а именно rebase. Ну и внимательно разобраться с конфликтами. Если это не знакомо или трудно можем списаться в Viribus unitis там и пересечся в дискорде и я покажу наглядно. Либо просто убери этот коммит с мержем и перезалей в свою ветку с перезаписью (git push -f)

2023-05-06 12:35 UTC, mrerro commented on PrinterApp/MouseOperations.cs
> +namespace PrintApp {
Не `PrintApp` а `PrinterApp` опечатка, поправить

2023-05-08 15:49 UTC, mrerro commented
@JR000 Я в общем отребейзился до последнего мейна можешь перезалить свою ветку этой https://github.com/profcomff/print-winapp/tree/wndproc и добавить последнюю правку https://github.com/profcomff/print-winapp/pull/54#discussion_r1186689979. При ребейзе были конфликты которые можно было разрулить только в ручную, а не через утилиты сравнения.

2023-05-08 18:06 UTC, mrerro commented
@JR000 что надумал, rebase сам хочешь победить? Если нет то просто открой новый ПР с веткой https://github.com/profcomff/print-winapp/tree/wndproc в ней все твои исправления с https://github.com/profcomff/print-winapp/pull/54/commits/f2108b9614a43c2f944d1c1d02bae21b15493c65.

2023-05-10 18:57 UTC, closed without merging